name: C/C++ CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm@sha256:116afba8df8453961de2936ffab20dd441edf4d682856c1ec8b0e53d7ed0bbf5

    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      with:
        fetch-depth: 1
        submodules: recursive

    - name: Get ctr_firm_builder commit
      run: echo "FIRM_BUILDER_COMMIT=$(git ls-remote https://github.com/derrekr/ctr_firm_builder.git HEAD | cut -f1)" >> $GITHUB_ENV

    - name: Cache ctr_firm_builder
      id: cache-firm-builder
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
      with:
        path: ctr_firm_builder
        key: ${{ runner.os }}-${{ env.FIRM_BUILDER_COMMIT }}

    - name: Install ctr_firm_builder dependencies
      if: steps.cache-firm-builder.outputs.cache-hit != 'true'
      run: |
        apt-get update
        apt-get -y install gcc

    - name: Build ctr_firm_builder
      if: steps.cache-firm-builder.outputs.cache-hit != 'true'
      run: |
        git clone --depth 1 --recurse-submodules https://github.com/derrekr/ctr_firm_builder.git
        cd ctr_firm_builder
        make

    - name: Build project
      run: |
        export PATH=$PWD/ctr_firm_builder:$PATH
        make nightly
        echo ${{ github.sha }} >> ./nightly/nightly_commit.txt

    - name: Upload artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: open_agb_firm_nightly
        path: ./nightly
        if-no-files-found: error
